# Screen settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = 60
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

# Shot settings
SHOT_RADIUS = 5